baseURL = "/"
languageCode = "en-us"
title = "Otago Repository for Core Analysis"
theme = "min_night"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    #post = "/:year/:month/:day/:slug/"




[params]
    #author = "Bob Dagg"
    description = "The Otago Repository for Core Analysis contains infrastructure and equipment that allows the detailed analysis of core samples including an iTrax XRF, a Geotek MSCL and a large lab area for logging and sampling cores."
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    #font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    #highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1


[[menu.main]]
    url = "/equipment/Equipment"
    name = "Equipment"
    weight = 3
    
[[menu.main]]
    url = "/form/Form"
    name = "Contact"
    weight = 4
    
[[menu.main]]
    url = "/Rates/rates"
    name = "Rates"
    weight = 5
    
# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
 
