baseURL = "/"
languageCode = "en-us"
title = "University of Otago Core Repository and Analytical Facility"
description = "An easy reading Hugo blog with night-mode."
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Nate Day"
    description = ""
    logo = "favicon/android-chrome-192x192.png"
    twitterAuthor = "@natedayta"
    githubUsername = "nathancday"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/equipment/Equipment"
    name = "Equipment"
    weight = 3
    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = ""
    name = ""
    weight = 1

[[menu.icon]]
    url = ""
    name = ""
    weight = 2

[[menu.icon]]
    url = ""
    name = ""
    weight = 3

[[menu.icon]]
    url = ""
    name = ""
    weight = 4

[[menu.icon]]
    url = ""
    name = ""
    weight = 5
