---
title: "Rates for Hire"
---


## Geotek

Internal University Use: $ 50/hr, min charge of 4 hours  
External Research Use: $80/hr  (non commercial entities i.e CRI’s, other universities etc)  
Commercial Use: $150/hr 

Training Fee of $200 + Geotek time 

## iTrax
Principal User Use: $100/hr (see list below incl students and collaborators)  
Outside Principal Group: $130/hr (non commercial entities i.e CRI’s, other universities etc)  
Commercial Use: $250/hr  

Training Fee of $200 + iTrax time  

## Technician Costs
$65/hour for the first 2 categories on both lists  
$90/hour for commercial work  


## iTrax Principal Users

### Division of Sciences  
#### Geology  
Prof. Dave Craw  
Dr. Chris Moy  
Dr. Christian Ohneiser  
Dr. Christina Riesselman  
Prof. Mark Stirling  
Dr. Virginia Toy  
Prof. James White  

#### Marine Science
Prof. Gary Wilson  

#### Chemistry
A. Prof Claudine Stirling  

### Division of Humanities
#### Geography
Prof. Sean Fitzsimons  

#### Anthropology & Archaeology:
Prof. Glenn Summerhayes  

